from src.others.constants import *
from src.others.structures import *
from src.models.squares import *

# This file defines all board squares

A1 = Square(FileIndex.kA,RankIndex.k1)
A2 = Square(FileIndex.kA,RankIndex.k2)
A3 = Square(FileIndex.kA,RankIndex.k3)
A4 = Square(FileIndex.kA,RankIndex.k4)
A5 = Square(FileIndex.kA,RankIndex.k5)
A6 = Square(FileIndex.kA,RankIndex.k6)
A7 = Square(FileIndex.kA,RankIndex.k7)
A8 = Square(FileIndex.kA,RankIndex.k8)

B1 = Square(FileIndex.kB,RankIndex.k1)
B2 = Square(FileIndex.kB,RankIndex.k2)
B3 = Square(FileIndex.kB,RankIndex.k3)
B4 = Square(FileIndex.kB,RankIndex.k4)
B5 = Square(FileIndex.kB,RankIndex.k5)
B6 = Square(FileIndex.kB,RankIndex.k6)
B7 = Square(FileIndex.kB,RankIndex.k7)
B8 = Square(FileIndex.kB,RankIndex.k8)

C1 = Square(FileIndex.kC,RankIndex.k1)
C2 = Square(FileIndex.kC,RankIndex.k2)
C3 = Square(FileIndex.kC,RankIndex.k3)
C4 = Square(FileIndex.kC,RankIndex.k4)
C5 = Square(FileIndex.kC,RankIndex.k5)
C6 = Square(FileIndex.kC,RankIndex.k6)
C7 = Square(FileIndex.kC,RankIndex.k7)
C8 = Square(FileIndex.kC,RankIndex.k8)

D1 = Square(FileIndex.kD,RankIndex.k1)
D2 = Square(FileIndex.kD,RankIndex.k2)
D3 = Square(FileIndex.kD,RankIndex.k3)
D4 = Square(FileIndex.kD,RankIndex.k4)
D5 = Square(FileIndex.kD,RankIndex.k5)
D6 = Square(FileIndex.kD,RankIndex.k6)
D7 = Square(FileIndex.kD,RankIndex.k7)
D8 = Square(FileIndex.kD,RankIndex.k8)

E1 = Square(FileIndex.kE,RankIndex.k1)
E2 = Square(FileIndex.kE,RankIndex.k2)
E3 = Square(FileIndex.kE,RankIndex.k3)
E4 = Square(FileIndex.kE,RankIndex.k4)
E5 = Square(FileIndex.kE,RankIndex.k5)
E6 = Square(FileIndex.kE,RankIndex.k6)
E7 = Square(FileIndex.kE,RankIndex.k7)
E8 = Square(FileIndex.kE,RankIndex.k8)

F1 = Square(FileIndex.kF,RankIndex.k1)
F2 = Square(FileIndex.kF,RankIndex.k2)
F3 = Square(FileIndex.kF,RankIndex.k3)
F4 = Square(FileIndex.kF,RankIndex.k4)
F5 = Square(FileIndex.kF,RankIndex.k5)
F6 = Square(FileIndex.kF,RankIndex.k6)
F7 = Square(FileIndex.kF,RankIndex.k7)
F8 = Square(FileIndex.kF,RankIndex.k8)

G1 = Square(FileIndex.kG,RankIndex.k1)
G2 = Square(FileIndex.kG,RankIndex.k2)
G3 = Square(FileIndex.kG,RankIndex.k3)
G4 = Square(FileIndex.kG,RankIndex.k4)
G5 = Square(FileIndex.kG,RankIndex.k5)
G6 = Square(FileIndex.kG,RankIndex.k6)
G7 = Square(FileIndex.kG,RankIndex.k7)
G8 = Square(FileIndex.kG,RankIndex.k8)

H1 = Square(FileIndex.kH,RankIndex.k1)
H2 = Square(FileIndex.kH,RankIndex.k2)
H3 = Square(FileIndex.kH,RankIndex.k3)
H4 = Square(FileIndex.kH,RankIndex.k4)
H5 = Square(FileIndex.kH,RankIndex.k5)
H6 = Square(FileIndex.kH,RankIndex.k6)
H7 = Square(FileIndex.kH,RankIndex.k7)
H8 = Square(FileIndex.kH,RankIndex.k8)
